[theme]
# O Rosa que você escolheu para botões e detalhes
primaryColor = "#ffffff18" 

# Fundo principal branco para manter a clareza
backgroundColor = "#9b0040"

# Cinza bem claro para a lateral, combinando com o branco
secondaryBackgroundColor = "#9b0040"

# Texto num tom grafite para não ser tão pesado quanto o preto puro
textColor = "#FFFFFF"

font = "sans serif"