[theme]
# Configuração de estilização do site

primaryColor = "#000000" # Para aba lateral e botãos

backgroundColor = "#9b0040" # Para o plano de fundo

secondaryBackgroundColor = "#e604753b" # Para os ícones clicáveis

textColor = "#FFFFFF" # Para o texto

font = "sans serif" # Fonte do texto