[theme]
# O Rosa que você escolheu para botões e detalhes
primaryColor = "#000000" 

# Fundo principal branco para manter a clareza
backgroundColor = "#9b0040"

# Cinza bem claro para a lateral, combinando com o branco
secondaryBackgroundColor = "#e604753b"

# Texto num tom grafite para não ser tão pesado quanto o preto puro
textColor = "#FFFFFF"

font = "sans serif"